# Generated by Django 2.2.8 on 2022-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingtask',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='programmingtask',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('c++', 'C++'), ('javascript', 'JavaScript')], default='python', max_length=10),
        ),
    ]
