# Generated by Django 2.2.8 on 2022-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220512_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingtask',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
    ]
