# Generated by Django 2.2.8 on 2022-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_programmingtask_solved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingtask',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
