# Generated by Django 2.2.8 on 2022-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingtask',
            name='max_plagiarism',
            field=models.FloatField(default=0),
        ),
    ]
