# Generated by Django 2.2.8 on 2022-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_programmingtask_max_plagiarism'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='chapters'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='course_banners'),
        ),
    ]
