# Generated by Django 2.2.8 on 2022-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220523_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingtasksolution',
            name='isplagiarized',
            field=models.BooleanField(default=False),
        ),
    ]
