# Generated by Django 2.2.8 on 2022-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_programmingtasksolution_plagiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
