# Generated by Django 2.2.8 on 2022-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_programmingtask_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingtask',
            name='input_description',
        ),
        migrations.RemoveField(
            model_name='programmingtask',
            name='input_example',
        ),
        migrations.RemoveField(
            model_name='programmingtask',
            name='output_description',
        ),
        migrations.RemoveField(
            model_name='programmingtask',
            name='output_example',
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProgrammingTask')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
