# Generated by Django 2.2.8 on 2022-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220523_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uniquenumber',
            field=models.CharField(default=None, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
